/* @generated by tools/futhark_abi_gen.py -- DO NOT EDIT BY HAND. */
/* Source manifest: main_gpu.json (Futhark 0.25.29., cuda) */
#include "main_gpu.h"
#include <stdbool.h>
#include <stdint.h>

/* Each assertion compares the real generated prototype against the
   signature implied by the manifest. A mismatch is a compile error, so
   stale generated C can never be linked against these bindings. */

typedef int (*abi_clip_matrix_global_norm_f32_t)(struct futhark_context *, struct futhark_f32_2d **, const struct futhark_f32_2d *, const float);
typedef int (*abi_embedding_backward_padded_t)(struct futhark_context *, struct futhark_f32_2d **, const struct futhark_i64_1d *, const struct futhark_i64_1d *, const struct futhark_f16_3d *, const struct futhark_f32_2d *);
typedef int (*abi_embedding_forward_padded_t)(struct futhark_context *, struct futhark_f16_3d **, const struct futhark_i64_1d *, const struct futhark_i64_1d *, const struct futhark_i64_1d *, const struct futhark_f16_2d *);
typedef int (*abi_embedding_spectral_normalize_t)(struct futhark_context *, struct futhark_f32_2d **, struct futhark_f32_1d **, struct futhark_f32_1d **, float *, float *, const struct futhark_f32_2d *, const struct futhark_f32_1d *, const struct futhark_f32_1d *, const int64_t, const float);
typedef int (*abi_embedding_sum_squares_t)(struct futhark_context *, float *, const struct futhark_f16_2d *);
typedef int (*abi_embedding_update_sfd_master_t)(struct futhark_context *, struct futhark_f32_2d **, struct futhark_f32_2d **, struct futhark_f32_2d **, const struct futhark_f32_2d *, const struct futhark_f32_2d *, const struct futhark_f32_2d *, const struct futhark_f32_2d *, const float, const float, const float, const int64_t, const float, const float, const float);
typedef int (*abi_graph_batch_encode_t)(struct futhark_context *, struct futhark_u64_1d **, struct futhark_f32_1d **, struct futhark_f32_1d **, struct futhark_f32_1d **, struct futhark_f32_1d **, struct futhark_i64_1d **, struct futhark_i64_1d **, const struct futhark_u64_1d *, const uint64_t);
typedef int (*abi_master_weights_to_f16_2d_t)(struct futhark_context *, struct futhark_f16_2d **, const struct futhark_f32_2d *);
typedef int (*abi_master_weights_to_f16_3d_t)(struct futhark_context *, struct futhark_f16_3d **, const struct futhark_f32_3d *);
typedef int (*abi_matmul_t)(struct futhark_context *, struct futhark_f32_2d **, const struct futhark_f32_2d *, const struct futhark_f32_2d *);
typedef int (*abi_rsf_forward_t)(struct futhark_context *, struct futhark_f16_2d **, const struct futhark_f16_2d *, const struct futhark_f16_2d *, const struct futhark_f16_2d *, const uint16_t, const uint16_t);
typedef int (*abi_rsf_stack_backward_gradients_fused_t)(struct futhark_context *, struct futhark_f32_3d **, struct futhark_f32_3d **, struct futhark_f16_3d **, float *, float *, float *, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const struct futhark_i64_1d *, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const bool, const float, const float, const float, const float, const float, const float);
typedef int (*abi_rsf_stack_forward_t)(struct futhark_context *, struct futhark_f16_3d **, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const uint16_t, const uint16_t);
typedef int (*abi_rsf_stack_inverse_t)(struct futhark_context *, struct futhark_f16_3d **, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const struct futhark_f16_3d *, const uint16_t, const uint16_t);
typedef int (*abi_scale_matrix_f32_t)(struct futhark_context *, struct futhark_f32_2d **, const struct futhark_f32_2d *, const float);
typedef int (*abi_stack_spectral_normalize_t)(struct futhark_context *, struct futhark_f32_3d **, float *, float *, const struct futhark_f32_3d *, const float, const int64_t);
typedef int (*abi_stack_update_sfd_master_t)(struct futhark_context *, struct futhark_f32_3d **, struct futhark_f32_3d **, struct futhark_f32_3d **, const struct futhark_f32_3d *, const struct futhark_f32_3d *, const struct futhark_f32_3d *, const struct futhark_f32_3d *, const float, const float, const float, const int64_t, const float, const float, const float);

_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_clip_matrix_global_norm_f32), abi_clip_matrix_global_norm_f32_t),
               "clip_matrix_global_norm_f32: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_embedding_backward_padded), abi_embedding_backward_padded_t),
               "embedding_backward_padded: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_embedding_forward_padded), abi_embedding_forward_padded_t),
               "embedding_forward_padded: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_embedding_spectral_normalize), abi_embedding_spectral_normalize_t),
               "embedding_spectral_normalize: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_embedding_sum_squares), abi_embedding_sum_squares_t),
               "embedding_sum_squares: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_embedding_update_sfd_master), abi_embedding_update_sfd_master_t),
               "embedding_update_sfd_master: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_graph_batch_encode), abi_graph_batch_encode_t),
               "graph_batch_encode: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_master_weights_to_f16_2d), abi_master_weights_to_f16_2d_t),
               "master_weights_to_f16_2d: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_master_weights_to_f16_3d), abi_master_weights_to_f16_3d_t),
               "master_weights_to_f16_3d: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_matmul), abi_matmul_t),
               "matmul: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_rsf_forward), abi_rsf_forward_t),
               "rsf_forward: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_rsf_stack_backward_gradients_fused), abi_rsf_stack_backward_gradients_fused_t),
               "rsf_stack_backward_gradients_fused: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_rsf_stack_forward), abi_rsf_stack_forward_t),
               "rsf_stack_forward: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_rsf_stack_inverse), abi_rsf_stack_inverse_t),
               "rsf_stack_inverse: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_scale_matrix_f32), abi_scale_matrix_f32_t),
               "scale_matrix_f32: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_stack_spectral_normalize), abi_stack_spectral_normalize_t),
               "stack_spectral_normalize: generated C ABI does not match manifest");
_Static_assert(__builtin_types_compatible_p(__typeof__(&futhark_entry_stack_update_sfd_master), abi_stack_update_sfd_master_t),
               "stack_update_sfd_master: generated C ABI does not match manifest");

